<?php

namespace system;
\date_default_timezone_set("America/Los_Angeles");
require_once '../autoload.php';
/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-08-10 at 18:39:45.
 */
class SettingsTest extends \PHPUnit_Framework_TestCase {
    /**
     * @var Settings
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Settings;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        $this->object = null;
    }

    /**
     * @covers system\Settings::read
     * @todo   Implement testRead().
     */
    public function testRead() {
        $data = $this->object->read("genericData");
        $this->assertEquals( "Not set", $data );
    }

}
