<?php

\date_default_timezone_set("America/Los_Angeles");
require_once '../autoload.php';
/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-08-10 at 18:39:45.
 */
class TokenStorageTest extends \PHPUnit_Framework_TestCase {
    public function testStore(){
        $testData = [
            "a"=>1,
            "b"=>2,
            "c"=>3
        ];
        $token = \model\security\Token::create(1, $testData);
        $tokenData = \business\storage\TokenStorage::create();
        $bool = $tokenData->store($token);
        $this->assertTrue( $bool, "Store returns a true value to note successful storage." );
        $tokenCopy = $tokenData->getById($token->getId());
        /* @var $tokenCopy \business\security\Token */
        $this->assertTrue( \is_object($tokenCopy), "The database does not return an object.");
        $storedData = $tokenCopy->getData();
        foreach( $testData as $key => $value ){
            $this->assertEquals( $testData[$key], $storedData[$key], "The stored data does not match the test data that was stored." );
        }
    }
}
